name: dartomite
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.1.0
  drift: ^2.21.0
  json_annotation: ^4.9.0
  mime: ^1.0.6
  path: ^1.9.1
  sqlite3: ^2.4.7

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.21.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
